let pizzaJson = [
    {id:1, name:'Mussarela', img:'images/pizza.png', price:[30.19, 34.30, 39.10], sizes:['100g', '530g', '860g'], description:'A pizza de mussarela é uma combinação clássica de massa fina, molho de tomate, e queijo mussarela derretido. Simples e deliciosa.'},
    {id:2, name:'Calabresa', img:'images/pizza2.png', price:[28.00, 31.00, 35.34], sizes:['320g', '530g', '860g'], description:'A pizza de calabresa é uma explosão de sabores com uma base de massa coberta por molho de tomate e generosas fatias de linguiça calabresa.'},
    {id:3, name:'Quatro Queijos', img:'images/pizza3.png', price:[37.45, 40.70, 45.90], sizes:['320g', '530g', '860g'], description:'A pizza de quatro queijos é uma explosão para os amantes de queijo. Sua base de massa é coberta com um delicioso molho de tomate e uma mistura de quatro queijos diferentes.'},
    {id:4, name:'Americana', img:'images/pizza4.png', price:[29.77, 32.00, 36.30], sizes:['320g', '530g', '860g'], description:'A pizza americana é conhecida por sua versatilidade e coberturas abundantes. Com uma massa tradicionalmente mais espessa, essa pizza é generosamente coberta com vários ingredientes.'},
    {id:5, name:'Paulista', img:'images/pizza5.png', price:[31.43, 34.00, 38.00], sizes:['320g', '530g', '860g'], description:'A pizza paulista reflete a diversidade gastronômica da cidade de São Paulo, Brasil. Geralmente apresenta uma massa fina e crocante, com coberturas que variam amplamente.'},
    {id:6, name:'Moda da Casa', img:'images/pizza6.png', price:[42.55, 44.00, 46.00], sizes:['320g', '530g', '860g'], description:'A pizza "moda da casa" é uma criação exclusiva da pizzaria, apresentando uma combinação única de ingredientes escolhidos pelo estabelecimento.'},
    {id:7, name:'Chocolate', img:'images/pizza7.png', price:[32.36, 34.00, 37.00], sizes:['320g', '530g', '860g'], description:'A pizza de chocolate é uma deliciosa variação da clássica pizza, transformando a tradicional receita salgada em uma sobremesa irresistível.'},
    {id:8, name:'Marguerita', img:'images/pizza8.png', price:[34.00, 37.50, 40.00], sizes:['320g', '530g', '860g'], description:'A pizza Margherita é uma verdadeira representação da simplicidade e da elegância da culinária italiana, absolutamente deliciosa, que celebra a beleza dos ingredientes básicos.'},
    {id:9, name:'Frango com Catupiry', img:'images/pizza9.png', price:[33.30, 36.00, 39.80], sizes:['320g', '530g', '860g'], description:'A pizza de frango com catupiry é uma deliciosa combinação que une o sabor suave e suculento do frango com a cremosidade irresistível do queijo catupiry.'}
];